---
- name: Imprimir URL del workflow en ejecución
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Mostrar URL del workflow actual
      debug:
        msg: "URL del workflow en ejecución: {{ workflow_url }}"
      when: workflow_url is defined

    - name: Mostrar mensaje si no hay URL disponible
      debug:
        msg: "No se encontró la variable workflow_url"
      when: workflow_url is not defined