---
- name: Imprimir URL del workflow en ejecución
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Mostrar URL del workflow actual
      ansible.builtin.debug:
        msg: "URL del workflow en ejecución: {{ lookup('env', 'TOWER_URL') }}//#/workflows/{{ lookup('env', 'TOWER_WORKFLOW_JOB_ID') }}"
