---
- name: Testear versión de workflow
  hosts: localhost
  tasks:
    - name: Obtener metadatos del controller
      awx.awx.controller_meta:
        register: controller_metadata

    - name: Mostrar ID del workflow
      debug:
        msg: "Job finalizado exitosamente en el workflow con id {{ controller_metadata.workflow_job_id }}"
