---
- name: Testear versión de workflow
  hosts: localhost
  tasks:
    - name: Obtener metadatos del controller
      awx.awx.controller_meta:
      register: controller_metadata

    - name: Mostrar  controller
      ansible.builtin.debug:
        msg: "controller es {{ controller_metadata }}"

    - name: Mostrar ID del workflow
      ansible.builtin.debug:
        msg: "Job finalizado exitosamente en el workflow con id {{ workflow_url}}"
